CREATE TABLE TAB_IDENTITY (ID INT AUTO_INCREMENT, DESCRITOR VARCHAR(20), PRIMARY KEY (ID));
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ("CLIENTE1");
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ("CLIENTE2");
INSERT INTO TAB_IDENTITY (DESCRITOR) VALUES ("CLIENTE3");
INSERT INTO TAB_IDENTITY (ID, DESCRITOR) VALUES (NULL, "CLIENTE4");
INSERT INTO TAB_IDENTITY (ID, DESCRITOR) VALUES (NULL, "CLIENTE5");
SELECT * FROM TAB_IDENTITY;

DELETE FROM TAB_IDENTITY WHERE ID = 5;

/* não importa se o 5 não existe mais, ele vai incrementar a partir do ultimo ID adicionado */ 
INSERT INTO TAB_IDENTITY (ID, DESCRITOR) VALUES (NULL, "CLIENTE6");

/* também é possivel forçar o número do ID mesmo com auto incremento */
INSERT INTO TAB_IDENTITY (ID, DESCRITOR) VALUES (100, "CLIENTE100");