/* criando a tabela vendas_sucos */
CREATE DATABASE vendas_sucos;

/* selecionando os caracteres disponiveis em uma tabela */
CREATE DATABASE vendas_sucos2 DEFAULT CHARACTER SET utf8;

/* excluindo a tabela */
DROP DATABASE IF EXISTS vendas_sucos2;

/* criando a tabela de produtos */
CREATE TABLE PRODUTOS
(CODIGO VARCHAR(10) NOT NULL,
DESCRITOR VARCHAR(100) NULL,
SABOR VARCHAR(50) NULL,
TAMANHO VARCHAR(50) NULL,
EMBALAGEM VARCHAR(50) NULL,
PRECO_LISTA FLOAT NULL,
PRIMARY KEY (CODIGO));

/* criando a tabela de vendedores */
CREATE TABLE VENDEDORES
(MATRICULA VARCHAR(5) NOT NULL,
NOME VARCHAR(100) NULL,
BAIRRO VARCHAR(50) NULL,
COMISSAO FLOAT NULL,
DATA_ADIMISSAO DATE NULL,
FERIAS BIT(1) NULL,
PRIMARY KEY (MATRICULA));

/* renomeando a coluna DATA_ADMISSAO */
ALTER TABLE VENDEDORES RENAME COLUMN DATA_ADIMISSAO TO DATA_ADMISSAO;

/* criando a tabela de vendas */
CREATE TABLE TABELA_DE_VENDAS
(NUMERO VARCHAR(5) NOT NULL,
DATA_VENDA DATE NULL,
CPF VARCHAR(11) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPOSTO FLOAT NULL,
PRIMARY KEY (NUMERO));

/* setando CPF (tabela de clientes) como foreingn key da TABELA_DE_VENDAS */
ALTER TABLE TABELA_DE_VENDAS ADD CONSTRAINT FK_CLIENTES
FOREIGN KEY (CPF) REFERENCES CLIENTES (CPF);

/* setando MATRICULA (tabela de vendedores) como foreign key da TABELA_DE_VENDAS */
ALTER TABLE TABELA_DE_VENDAS ADD CONSTRAINT FK_VENDEDORES
FOREIGN KEY (MATRICULA) REFERENCES VENDEDORES (MATRICULA);

/* renomeando a tabela_de_vendas para Notas */
ALTER TABLE tabela_de_vendas RENAME Notas;