SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS SOMA_LIMITE FROM tabela_de_clientes
GROUP BY ESTADO HAVING SUM(LIMITE_DE_CREDITO) > 900000;

SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS MAIOR_PRECO, MIN(PRECO_DE_LISTA) AS MENOR_PRECO FROM tabela_de_produtos
GROUP BY EMBALAGEM HAVING SUM(PRECO_DE_LISTA) <= 80;

SELECT * FROM tabela_de_produtos;

#Exercício
#Quais foram os clientes que fizeram mais de 2000 compras em 2016?
SELECT * FROM notas_fiscais;

SELECT CPF,COUNT(CPF) AS NÚMERO_DE_COMPRAS FROM notas_fiscais WHERE YEAR(DATA_VENDA) = "2016"
GROUP BY CPF HAVING NÚMERO_DE_COMPRAS > 2000;

SELECT * FROM notas_fiscais WHERE YEAR(DATA_VENDA) = "2016";
