#Código, tamanho, sabor
SELECT * FROM tabela_de_produtos;
#quantidade
SELECT * FROM itens_notas_fiscais;
#DATA_VENDA
SELECT * FROM notas_fiscais;

SELECT 
    SABOR,
    LITROS_SABOR.ANO,
    SUM(CASE
        WHEN CHAR_LENGTH(CONVERT( TAMANHO , SIGNED)) = 1 THEN (TAMANHO * 1000) * LITROS_SABOR.QUANTIDADE
        WHEN CHAR_LENGTH(CONVERT( TAMANHO , SIGNED)) > 1 THEN TAMANHO * LITROS_SABOR.QUANTIDADE
    END) AS TOTAL_LITROS,
    ROUND((LITROS_SABOR.QUANTIDADE / LITROS_TOTAL.QUANTIDADE) * 100,
            2) AS PORCENTAGEM
FROM
    (SELECT 
			TP.TAMANHO,
            TP.SABOR,
            YEAR(NF.DATA_VENDA) AS ANO,
            SUM(INF.QUANTIDADE) AS QUANTIDADE
    FROM
        tabela_de_produtos TP
    INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
    INNER JOIN notas_fiscais NF ON INF.NUMERO = NF.NUMERO
    WHERE
        YEAR(NF.DATA_VENDA) = 2016
    GROUP BY SABOR , ANO
    ORDER BY QUANTIDADE DESC) AS LITROS_SABOR
        INNER JOIN
    (SELECT 
        YEAR(NF.DATA_VENDA) AS ANO,
            SUM(INF.QUANTIDADE) AS QUANTIDADE
    FROM
        tabela_de_produtos TP
    INNER JOIN itens_notas_fiscais INF ON TP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO
    INNER JOIN notas_fiscais NF ON INF.NUMERO = NF.NUMERO
    WHERE
        YEAR(NF.DATA_VENDA) = 2016
    GROUP BY ANO
    ORDER BY QUANTIDADE DESC) AS LITROS_TOTAL
GROUP BY SABOR , LITROS_SABOR.ANO
ORDER BY TOTAL_LITROS DESC;


    
    
    






